# Generated by Django 3.0.3 on 2020-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bride', '0002_auto_20200310_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_num', models.TextField()),
                ('name', models.TextField(max_length=40)),
                ('stud_class', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
