# Generated by Django 3.0.3 on 2020-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bride', '0003_auto_20200310_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bride',
            name='department',
        ),
        migrations.RemoveField(
            model_name='bride',
            name='roll_num',
        ),
        migrations.RemoveField(
            model_name='bride',
            name='stud_class',
        ),
        migrations.AddField(
            model_name='bride',
            name='brand',
            field=models.CharField(default='anonymous', max_length=30),
        ),
        migrations.AddField(
            model_name='bride',
            name='describe',
            field=models.TextField(default='About the product specs'),
        ),
        migrations.AddField(
            model_name='bride',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bride',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bride',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
