# Generated by Django 3.0.3 on 2020-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bride', '0004_auto_20200310_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bride',
            name='email',
        ),
        migrations.AddField(
            model_name='bride',
            name='size',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
