# Generated by Django 3.0.4 on 2020-03-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bride', '0006_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bride',
            name='price',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
