# Generated by Django 3.0.4 on 2020-03-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bride', '0007_bride_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bride',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
