# Generated by Django 3.0.4 on 2020-03-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bride', '0010_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('product_id', models.IntegerField(null=True)),
            ],
        ),
    ]
